export const FETCH_TODO = "FETCH_TODO";
export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS";
export const FETCH_TODO_FALSE = "FETCH_TODO_FALSE";
export const DELETE_TODO_ITEMS = "DELETE_TODO_ITEMS";

export const FETCH_LIST_RENDER_SUCCESS = "FETCH_LIST_RENDER_SUCCESS";
export const FETCH_LIST_RENDER = "FETCH_LIST_RENDER";

export const ON_OPEN_FORM = "ON_OPEN_FORM";
export const ON_CLOSE_FORM = "ON_CLOSE_FORM";
export const ADD_DATA = "ADD_DATA";
export const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS";
export const ADD_DATA_FALSE = "ADD_DATA_FALSE";
export const ON_CLICK_EDIT_ITEM = "ON_CLICK_EDIT_ITEM";
export const EDIT_DATA = "EDIT_DATA";

export const STATUS_EDIT_DATA_SUCCESS = "STATUS_EDIT_DATA_SUCCESS";
export const STATUS_EDIT_DATA_FALSE = "STATUS_EDIT_DATA_FALSE";
export const ACTION_FILLTER = "ACTION_FILLTER";
export const ACTION_FILLTER_SUCCESS = "ACTION_FILLTER_SUCCESS";
export const ACTION_FILLTER_FALSE = "ACTION_FILLTER_FALSE";
export const ACTION_PAGE = "ACTION_PAGE";
export const RENDER_PAGE = "RENDER_PAGE";
export const GET_PAGE_SUCCESS = "GET_PAGE_SUCCESS";
